spring.application.name=localservice
server.port=${PORT:8089}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/localservice}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:localservice}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:localservice}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

app.seed.enabled=false

razorpay.key_id=${RAZORPAY_KEY_ID:}
razorpay.key_secret=${RAZORPAY_KEY_SECRET:}

gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent}